passenger_version: '1:5.0.8-1~`lsb_release -sc`1'
passenger_ruby: "#{ruby_path}/bin/ruby"
passenger_listen_port: 80
passenger_listen_ssl_port: 443
max_app_connections: 20

role_dependencies:
  passenger: [apache]

roles:
  passenger:
    packages: [libcurl4-openssl-dev, libapache2-mod-xsendfile, libapache2-mod-passenger]
    rolling_restart_port: "#{passenger_listen_port}"

  web_tools:
    rolling_restart_port: "#{web_tools_port}"
